linters-settings:
  staticcheck:
    checks: ["all"]
  gofumpt:
    module-path: "wireguard-admin"
    extra-rules: true
  goimports:
    local-prefixes: "wireguard-admin"

linters:
  enable:
    - unused
    - errcheck
    - gosimple
    - goimports
    - gofumpt
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - rowserrcheck
    - unconvert
    - unparam

run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 1
  tests: false
  skip-dirs:
    - ui
  skip-dirs-use-default: false